import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Topbar } from "@/components/topbar";

// Variables CSS que expone el paquete geist/font
// GeistSans.variable => --font-geist-sans
// GeistMono.variable => --font-geist-mono

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body className={`${GeistSans.className} antialiased bg-gray-50`}>        
        <div className="min-h-dvh w-full grid md:grid-cols-[16rem_1fr]">
          <Sidebar />
          <div className="flex flex-col min-w-0">
            <Topbar />
            <main className="p-4 md:p-6 w-full max-w-[1400px] mx-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
