import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { Topbar } from "@/components/topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>        
        <div className="min-h-dvh w-full grid md:grid-cols-[16rem_1fr]">
          <Sidebar />
          <div className="flex flex-col min-w-0">
            <Topbar />
            <main className="p-4 md:p-6 w-full max-w-[1400px] mx-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
