[project]
name = "pricing-engine"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30"
]

[project.scripts]
engine = "uvicorn app.main:app --host 0.0.0.0 --port 8000"


