name: n8n-import

on:
  workflow_dispatch:
  push:
    paths:
      - 'services/n8n-flows/workflows/**'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install n8n CLI
        run: npm i -g n8n
      - name: Import workflows
        env:
          N8N_HOST: ${{ secrets.N8N_HOST }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        run: n8n import:workflow --separate --input services/n8n-flows/workflows --yes


